language: cpp
compiler: gcc
sudo: required
dist: trusty
    
before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-trusty -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update

install:
  - sudo apt-get install g++-7 gcc-7
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90
  - sudo apt-get install qt510base
  #- "sudo apt-get install dh-make freetds-common libbluetooth3 libegl1-mesa-drivers libmng2 libmtdev1
  #libopenal-data libopenal1 libopenvg1-mesa libopus0 libsdl2-2.0-0 libsnappy1
  #libsybdb5 libwayland-egl1-mesa libwebp5 libwebpdemux1 libxcb-icccm4
  #libxcb-image0 libxcb-keysyms1 libxcb-render-util0 libxcb-xinerama0 qt510base
  #qt510connectivity qt510gamepad qt510graphicaleffects qt510imageformats 
  #qt510location qt510multimedia qt510quickcontrols qt510quickcontrols2 
  #qt510remoteobjects qt510script qt510scxml qt510sensors qt510serialbus 
  #qt510serialport qt510speech qt510svg qt510tools qt510translations 
  #qt510webchannel qt510websockets qt510x11extras qt510xmlpatterns qt510charts-no-lgpl"
  
script:
  - source /opt/qt510/bin/qt510-env.sh
  - /opt/qt510/bin/qmake Loja.pro
  - make -j3
  
  # TODO:
  # cache ccache cache folder?
  # cache /usr/bin
  # cache qt folder /opt/qt?